"""
Django settings for dayone project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
#项目绝对路径
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1f9zzme&=)@c5#eawx-is3tzwwhu3$t89ba)sllu7p&1(9x%k&'

# SECURITY WARNING: don't run with debug turned on in production!

#调试状态true 项目上线改为false
DEBUG = True

#如果是调试状态我们在下面列表什么都不填写,如果是生产状态里面填写["*"]代表所有的
ALLOWED_HOSTS = []


# Application definition

#代表项目里面所需要安装的应用response
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'testone'
)

#中间键
MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

#指向urls
ROOT_URLCONF = 'dayone.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #指定templates的路径BASE_DIR项目文件夹路径
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#创建套接字路径
WSGI_APPLICATION = 'dayone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

#数据库
DATABASES = {
    'default': {
        #设置使用什么数据库mysql
        'ENGINE': 'django.db.backends.mysql',
        #配置数据库自己命令创建
        'NAME': 'day1',
        'USER': 'root',
        'PASSWORD':'1234',
        'HOST':'localhost',
        'PORT':'3306',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

#设置语言
LANGUAGE_CODE = 'zh-CN'

#设置时区
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

#true为国际时间false为当前配置时间
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
